### ISSUE TITLE
Change black header and footer to be dark grey

### ISSUE THREAD

**Issue by longhotsummer** [Code4SA/styles#6]
The black is very stark. The dark grey @xybrnet used for http://code4sa.org/winterschool/ works very well. We may want to do the same thing for the black text.

**Comment by longhotsummer** [comment]
@xybrnet curious to get your input here?

**Comment by xybrnet** [comment]
@longhotsummer I definitely agree. I think we could even replace all black with the dark grey. (Or darker if need be)
